version: '3.8'
services:

  eureka-server:
    container_name: eureka
    image: asingh27/eureka-server:v1
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka


  first-service:
    container_name: first-service
    build: ./first-service
    ports:
      - "8081:8080"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  second-service:
    container_name: second-service
    build: ./second-service
    ports:
      - "8082:8080"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  third-service:
    container_name: third-service
    build: ./third-service
    ports:
      - "8083:8080"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "8929:8929"
      - "8080:80"
      - "443:443"
    volumes:
      - gitlab-data:/var/opt/gitlab
    restart: always

  jira:
    image: atlassian/jira-software:latest
    ports:
      - "8084:8080"
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jiradb
      - ATL_JDBC_USER=jirauser
      - ATL_JDBC_PASSWORD=jirapassword
      - ATL_JDBC_DRIVER=org.postgresql.Driver
    volumes:
      - jira-data:/var/atlassian/jira
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=jiradb
      - POSTGRES_USER=jirauser
      - POSTGRES_PASSWORD=jirapassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  gitlab-data:
  jira-data:
  postgres-data:
